language: scala
sudo: false

jdk:
  - oraclejdk8

scala:
  - 2.11.12
  - 2.12.4

script: sbt -Dcoveralls.disable ++$TRAVIS_SCALA_VERSION clean test

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $HOME/.zinc

# Coveralls disabled due to https://github.com/scoverage/sbt-coveralls/issues/102

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
